package com.bhadabazaar.BhadaBazaar.domain.enums;

public enum ItemCategory {
    JODHPURI, INDOWESTERN, LEHENGA, JEWELLERY, SHERWANI, SAREE, GOWN, SUITS, KURTA, CHANIYACHOLI, ANARKALI, SHARARA, NEHRUJACKET, BLAZER, BRIDAL_LEHENGA, GHARARA, PATHANI, BANDHGALA, ACHKAN, DHOTI_KURTA, HALF_SAREE, MEKHELA_CHADOR, PHERAN
}

