spring.application.name=BhadaBazaar

# Security logging
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.security.web.access.intercept.AuthorizationFilter=TRACE

# Database Configuration
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# JWT Configuration
application.security.jwt.secret-key=${JWT_SECRET_KEY}
application.security.jwt.expiration=86400000

# File Upload Configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=20MB

# Cloudflare Turnstile
cloudflare.turnstile.secret-key=${TURNSTILE_SECRET_KEY}
cloudflare.turnstile.url=${TURNSTILE_URL}

# Twilio Configuration
twilio.account-sid=${TWILIO_ACCOUNT_SID}
twilio.auth-token=${TWILIO_AUTH_TOKEN}
twilio.phone-number=${TWILIO_PHONE_NUMBER}

# Cloudflare Configuration
cloudflare.account-id=${CLOUDFLARE_ACCOUNT_ID}
cloudflare.api-token=${CLOUDFLARE_API_TOKEN}
cloudflare.image-delivery-url=${CLOUDFLARE_IMAGE_DELIVERY_URL}

# Render Port
server.port=${PORT:8080}



